<?php
printf("//// HIGHLY EXPERIMENTAL!!! Code generated by --codegendirect \n");
printf("//// TODO \n");
printf("\n");
printf("///  IP === r$ipidx \n");
printf("///  ^^^^^^^^^\n");
$regs = []; $regnames = []; $regpercents = [];
foreach($cpustate as $k=>$v) {
    $regnames[] = "r{$k}";
    $regpercents[] = "%9d";
    $regs[] = sprintf("r{$k}={$v}"); 
}
printf("int %s;\n", join(',',$regs));
printf("char _regsbuffer[255];\n");
printf("char * Elf_regs2string(){");
echo  ('  sprintf(_regsbuffer, "R:['.join(',',$regpercents).']", '.join(',',$regnames).");");
printf("  return _regsbuffer; ");
printf("}\n");
printf("bool Elf_emulate(long maxCount, long *actualIterationCount)\n");
printf("{\n");
printf("  long c=0;\n");
printf("  int *ip = &r$ipidx; \n");
printf("  while(c<maxCount){ \n");
printf("    r{$ipidx}++;\n");
printf("    c++;\n");
printf("  }\n");
printf("  *actualIterationCount += c;\n");
printf("  return true;\n");
printf("}\n");
