CXX = clang++-7
CPPFLAGS=-std=c++17 -Wall -pedantic -Ofast -march=native -mtune=native -mavx
BINARIES= day19 day19TranspiledElfProgram_Direct day19TranspiledElfProgram_Switch

all: $(BINARIES)

clean:
	rm -rf $(BINARIES)
